spring.application.name=demo
spring.datasource.url=jdbc:ucanaccess://C:/MyProfile/Profile.accdb
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none